version: '3'

#Define services
services:

  #PostgreSQL Database for the application
  db-postgres:
    image: "postgres:alpine"
    container_name: postgres-piscina-limpa
    #Volume mounted for database for the storage
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432 # Forward the exposed port 5432 on the container to port 5432 on the host machine

    #Environment variable for DB name, user and password
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

#Volumes for DB data
volumes:
  postgres-data:
